export const palabrasClave = [
  // Español 
  "quien te ha desarrollo",
  "quien te ha creado",
  "quien te programo",
  "quien te crea",
  "quien te hizo",
  "quien te realizo",
  "quien te realiza",
  "quien te programa",
  "quien te diseña",
  "quien te diseño",
  "quien creo esto",
  "quien ha creado esto",
  "quien ha creodo esta app",
  "quien hizo esta app",
  "quién hizo esta app",
  "quien hizo esta aplicación",
  "quien creo esta app",
  "quien creó esta app",
  "quien programo esta app",
  "quien programó esta app",
  "quien desarrollo esta app",
  "quien desarrolló esta app",
  "quien diseño esta app",
  "quien diseñó esta app",
  "quien construyo esta app",
  "quien construyó esta app",
  "quien realizo esta app",
  "quien realizó esta app",
  "quien fabrico esta app",
  "quien fabricó esta app",
  "quien hizo esta pagina",
  "quien hizo esta página",
  "quien creo esta pagina",
  "quien creó esta página",
  "quien desarrollo esta web",
  "quien desarrolló esta web",
  "quien diseño esta web",
  "quien diseñó esta web",
  "quien programo esta web",
  "quien programó esta web",
  "quien construyo esta web",
  "quien construyó esta web",
  "quien fabrico esta web",
  "quien fabricó esta web",
  "quien creo esta inteligencia artificial",
  "quien creó esta inteligencia artificial",
  "quien desarrollo esta inteligencia artificial",
  "quien desarrolló esta inteligencia artificial",
  "quien diseñó esta inteligencia artificial",
  "quien hizo esta inteligencia artificial",
  "quien creo este chat",
  "quien creó este chat",
  "quien desarrollo este chat",
  "quien desarrolló este chat",
  "quien hizo esta aplicación web",
  "quien creo esta aplicación web",
  "quien creó esta aplicación web",
  "quien programo esta página",
  "quien programó esta página",
  "quien programo este chat",
  "quien programó este chat",
  "como se hizo esta app",
  "como se hizo esta web",
  "como se desarrollo esta app",
  "como se desarrolló esta app",
  "como se desarrollo esta web",
  "como se desarrolló esta web",
  "como se programo esta app",
  "como se programó esta app",
  "como se programo esta web",
  "como se programó esta web",
  "como se creo esta app",
  "como se creó esta app",
  "como se creo esta página",
  "como se creó esta página",
  "como se creo este sitio",
  "como se creó este sitio",
  "como fue creada esta app",
  "quien te creo",  
  "quien te ha creo", 
  "como fue creada esta web",
  "como fue desarrollada esta app",
  "como fue desarrollada esta página",
  "quien es el creador de esta app",
  "quien es el creador de esta web",
  "quien la creo",
  "quien la creó",
  "quien la hizo",
  "quien la desarrollo",
  "quien la desarrolló",
  "quien la programo",
  "quien la programó",
  "quien la construyo",
  "quien la construyó",

  // Inglés 🇬🇧
  "who made this app",
  "who created this app",
  "who developed this app",
  "who built this app",
  "who designed this app",
  "who coded this app",
  "who programmed this app",
  "who engineered this app",
  "who invented this app",
  "who is behind this app",
  "who is the creator of this app",
  "who's the creator of this app",
  "who created this website",
  "who made this website",
  "who built this website",
  "who designed this website",
  "who developed this website",
  "who coded this website",
  "who programmed this website",
  "who is behind this website",
  "who is the developer of this app",
  "who is the developer of this website",
  "who's behind this app",
  "who's behind this website",
  "how was this app created",
  "how was this app built",
  "how was this app made",
  "how was this app developed",
  "how was this app programmed",
  "how was this app designed",
  "how was this website made",
  "how was this website created",
  "how was this website developed",
  "how was this website built",
  "how did they make this app",
  "how did they make this website",
  "how did they build this app",
  "how did they build this website",
  "how did they develop this app",
  "how did they develop this website",
  "how was this ai created",
  "Who created you?",
  "Who created you?",
  "who made this ai",
  "who created this ai",
  "who built this ai",
  "who developed this ai",
  "who is behind this ai",
  "who created this chat",
  "who built this chat",
  "who made this chat",
  "who developed this chat",
  "who's the creator of this chat",
  "who created this bot",
  "who made this bot",
  "who built this bot",
  "who created this",
  "who coded this bot"
];
